name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:   
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.18
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: github-metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: GrimaudNathan
          template: classic
          base: header, activity, community
          config_timezone: Europe/Pariq

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: B
