name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: GrimaudNathan
          template: terminal
          base: header, metadata, activity
          config_timezone: Europe/Paris
          
          #calendar plugin
          plugin_isocalendar: yes
